version: "3"
services:
    api:
        image: myapi:latest
        container_name: api
        build:
            context: ../
            dockerfile: ./src/Api/Dockerfile/
        ports:
            - "8080:8080"
            - "8081:8081"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - sqlserver
        restart: always
        networks: 
            - default
    sqlserver:
        image: mcr.microsoft.com/mssql/server
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_PID: "Developer"
          MSSQL_SA_PASSWORD: "MyPass@word"
        ports:
          - "1433:1433"
        volumes:
          - sql_serve_data:/var/opt/mssql
        networks:
            - default
volumes:
  sql_serve_data:
    driver: local

networks:
    default:
        name: network_default